Block on fip creation before starting the ping test.
We wait for the fip to be reachable during ~1minutes before starting
the ping test.  We fail if it's not reachable in that time frame.

Change-Id: I20cecd06834ef424599d9e281f0d6a6434f584a5
Closes-Bug: #1895829
(cherry picked from commit 306aa3b1996daddd2a81f6045ebbe47550bbc128)
(cherry picked from commit f9cc51478bfbcde96a81917754d320f2ba8ca03f)

diff --git a/templates/l3_agent_start_ping.sh.j2 b/templates/l3_agent_start_ping.sh.j2
--- a/templates/l3_agent_start_ping.sh.j2
+++ b/templates/l3_agent_start_ping.sh.j2
@@ -13,4 +13,16 @@ else
     {% endif %}
     source {{ working_dir }}/vm_ip.sh
 fi
+
+# Block 1 minute for the fip to be ready.
+cpt=1
+while ! ping -c 1 -w 1 "${VM_IP}"; do
+    echo "Waiting for fip to be ready ... for $cpt seconds"
+    if [ $cpt -gt 60 ]; then
+        echo "The fip ${VM_IP} took more than 1 minute to be available, aborting"
+        exit 1
+    fi
+    cpt=$((cpt+1))
+done
+
 ping -D ${VM_IP} >> ~/ping_results_$(date +%Y%m%d%H%M).log &
