workload launch refactor to support continuous control plane test.
This refactor paves the way to support continuous control plane test.

Added:
- trigger error when openstack command fails during creation;
- add a trap exit to make sure cleanup is always trigger in sanity;
- add a sanityfast mode to fail fast during continuous testing;
- add more test on created resources like cinder vol and fip;
- remove leftover ~/instance_.. file during sanity;

Sanity mode, we add a trap at exit to support cleanup. This ensures
that cleanup is triggered if any openstack command fail so that we
don't need explicit test.

During the teardow, we don't trigger new error for openstack command
as the state of the overcloud is at that point unknown and the best
course of action is just to return an error at that point.

Change-Id: I1e15ccb5a13e253da545efb6b1a23e4b20ef3faa
(cherry picked from commit 1dda7e142eade0035eef141b2c2815e2df3b2d02)

diff --git a/templates/workload_launch.sh.j2 b/templates/workload_launch.sh.j2
--- a/templates/workload_launch.sh.j2
+++ b/templates/workload_launch.sh.j2
@@ -6,14 +6,53 @@
 #               SRIOV
 #   - sanity:   spawn VM with floating/external ip assert it's ssh'able,
 #               delete VM and associated resources
+#   - sanityfast: same than sanity but fails faster
+#
 #   - cleanup:  clean up VM and other elements created previously
 #
+set -o pipefail
+
+IN_TEARDOWN=false
+FAST=""
 
 if [[ -n ${1} ]]; then
     MODE="${1}"
 else
     MODE="workload"
 fi
+
+# Run openstack command with an error check. This will trigger the
+# cleanup_on_exit trap for sanity and sanityfast mode. This doesn't
+# work for command expansion - $(...) expression.
+function os_cmd {
+    set -e
+    openstack "$@"
+    set +e
+}
+
+# This function get installed as a trap in sanity and sanityfast.
+cleanup_on_exit() {
+    RC=$?
+    echo "Tearing down with rc=$RC"
+    set +e
+    # We guard against failure during teardown.
+    if ! ${IN_TEARDOWN}; then
+        if [ -n "${FAST}" ]; then
+            sanity_teardown $FAST
+        else
+            sanity_teardown
+        fi
+    else
+        # We are in teardown, just abort.
+        echo "Failed during Teardown."
+        exit 64
+    fi
+    if [ -n "${INSTANCE_NAME}" -a -e "${HOME}/${INSTANCE_NAME}" ]; then
+        echo "Deleting ~/${INSTANCE_NAME}"
+        rm -f "${HOME}/${INSTANCE_NAME}"
+    fi
+    exit $RC
+}
 
 function prepare_env {
 
@@ -42,11 +81,10 @@ function prepare_env {
     export OS_SHARE_API_VERSION=2.57
     export OS_VOLUME_API_VERSION=3.62
     {%- endif %}
-
 }
 
 function sanity_check {
-    local timeout_seconds=180
+    local timeout_seconds=${1:-180}
     local elapsed_seconds=0
 
     echo "Waiting for compute services to be up"
@@ -65,20 +103,23 @@ function sanity_check {
 }
 
 function sanity_teardown {
+    IN_TEARDOWN=true
     # remove auxiliary resources
 
-    local timeout_seconds=180
+    local timeout_seconds=${1:-180}
     local elapsed_seconds=0
-
     {% if workload_sriov | bool -%}
     openstack port delete ${SRIOV_PORT}
     {% else -%}
-    echo "Remove ${INSTANCE_FIP} from ${INSTANCE_NAME}"
-    openstack server remove floating ip ${INSTANCE_NAME} ${INSTANCE_FIP}
-    grep ${INSTANCE_FIP} vm_ip.sh  && rm vm_ip.sh
+    if [ -n "${INSTANCE_FIP}" ]; then
+        echo "Remove ${INSTANCE_FIP} from ${INSTANCE_NAME}"
+        openstack server remove floating ip ${INSTANCE_NAME} ${INSTANCE_FIP}
+        grep ${INSTANCE_FIP} vm_ip.sh  && rm vm_ip.sh
 
-    echo "Delete floating ip ${INSTANCE_FIP}"
-    openstack floating ip delete ${INSTANCE_FIP}
+        echo "Delete floating ip ${INSTANCE_FIP}"
+        openstack floating ip delete ${INSTANCE_FIP}
+    fi
+
     {%- endif %}
 
     echo "Remove VM ${INSTANCE_NAME}"
@@ -90,32 +131,34 @@ function sanity_teardown {
             break
         fi
         sleep 5
-        elapsed_seconds=$(( ${elapsed_seconds} + 5 ))
+        elapsed_seconds=$((elapsed_seconds + 5))
         if [ $elapsed_seconds -ge $timeout_seconds ]; then
             echo "FAILURE: Failed to remove instance ${INSTANCE_NAME}"
             exit 1
         fi
     done
 
-    echo "Remove cinder volume ${CINDER_VOL_ID}"
-    openstack volume delete ${CINDER_VOL_ID}
+    if [ -n "${CINDER_VOL_ID}" ]; then
+        echo "Remove cinder volume ${CINDER_VOL_ID}"
+        openstack volume delete ${CINDER_VOL_ID}
 
-    while true; do
-        openstack volume list -f value -c ID | grep -q ${CINDER_VOL_ID}
-        if [[ ${?} -eq 1 ]]; then
-            echo "The volume ${CINDER_VOL_ID} successfully removed"
-            break
-        fi
+        elapsed_seconds=0
+        while true; do
+            openstack volume list -f value -c ID | grep -q ${CINDER_VOL_ID}
+            if [[ ${?} -eq 1 ]]; then
+                echo "The volume ${CINDER_VOL_ID} successfully removed"
+                break
+            fi
 
-        sleep 5
-        elapsed_seconds=$(( ${elapsed_seconds} + 5 ))
+            sleep 5
+            elapsed_seconds=$((elapsed_seconds + 5 ))
 
-        if [ $elapsed_seconds -ge $timeout_seconds ]; then
-            echo "FAILURE: Failed to remove the volume ${CINDER_VOL_ID}"
-            exit 1
-        fi
-    done
-
+            if [ $elapsed_seconds -ge $timeout_seconds ]; then
+                echo "FAILURE: Failed to remove the volume ${CINDER_VOL_ID}"
+                exit 1
+            fi
+        done
+    fi
     echo "Clear default gateway from ${TENANT_NET_NAME}_router"
     openstack router unset --external-gateway ${TENANT_NET_NAME}_router
 
@@ -145,11 +188,14 @@ function sanity_teardown {
 
     echo "Remove file ${IMAGE_FILE}"
     rm -Rf $(dirname ${IMAGE_FILE})
-
+    IN_TEARDOWN=false
 }
 
 function workload_launch {
     # create workload
+    timeout_seconds=${1:-120}
+    ssh_timeout_seconds=${1:-180}
+
     ## create image
     openstack image list | grep ${IMAGE_NAME}
 
@@ -174,14 +220,14 @@ function workload_launch {
     openstack keypair list | grep ${KEYPAIR_NAME}
     if [ $? -ne 0 ]; then
         echo "Creating keypair ${KEYPAIR_NAME}"
-        openstack keypair create --public-key ~/.ssh/id_rsa.pub ${KEYPAIR_NAME}
+        os_cmd keypair create --public-key ~/.ssh/id_rsa.pub ${KEYPAIR_NAME}
     fi
 
     ## create flavor
     openstack flavor list | grep ${FLAVOR_NAME}
     if [ $? -ne 0 ]; then
         echo "Creating flavor ${FLAVOR_NAME}"
-        openstack flavor create --vcpus {{ workload_vcpu }} \
+        os_cmd flavor create --vcpus {{ workload_vcpu }} \
             --ram {{ workload_memory }} \
             --disk {{ workload_disk }} \
             --swap {{ workload_swap }} \
@@ -193,13 +239,13 @@ function workload_launch {
     if [ $? -ne 0 ]; then
         NAMESERVER=$(grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' /etc/resolv.conf  | head -1)
         echo "Creating router ${TENANT_NET_NAME}_router"
-        openstack router create ${TENANT_NET_NAME}_router
+        os_cmd router create ${TENANT_NET_NAME}_router
 
         echo "Creating network ${TENANT_NET_NAME}"
-        openstack network create ${TENANT_NET_NAME}
+        os_cmd network create ${TENANT_NET_NAME}
 
         echo "Creating subnet ${TENANT_NET_NAME}_subnet"
-        openstack subnet create \
+        os_cmd subnet create \
             --subnet-range 192.168.0.0/24 \
             --allocation-pool start=192.168.0.10,end=192.168.0.100 \
             --gateway 192.168.0.254 \
@@ -208,27 +254,27 @@ function workload_launch {
             ${TENANT_NET_NAME}_subnet
 
         echo "Add subnet ${TENANT_NET_NAME}_subnet to router ${TENANT_NET_NAME}_router"
-        openstack router add subnet  ${TENANT_NET_NAME}_router ${TENANT_NET_NAME}_subnet
+        os_cmd router add subnet  ${TENANT_NET_NAME}_router ${TENANT_NET_NAME}_subnet
 
         echo "Set external-gateway for ${TENANT_NET_NAME}_router"
-        openstack router set --external-gateway ${EXTERNAL_NET_NAME} ${TENANT_NET_NAME}_router
+        os_cmd router set --external-gateway ${EXTERNAL_NET_NAME} ${TENANT_NET_NAME}_router
     fi
 
     ## create security group
     openstack security group list | grep ${SECGROUP_NAME}
     if [ $? -ne 0 ]; then
         echo "Creating security group ${SECGROUP_NAME}"
-        openstack security group create ${SECGROUP_NAME}
+        os_cmd security group create ${SECGROUP_NAME}
 
         echo "Creating rules for ports 22,80,443 in security group ${SECGROUP_NAME}"
-        openstack security group rule create --proto icmp ${SECGROUP_NAME}
-        openstack security group rule create --proto tcp --dst-port 22 ${SECGROUP_NAME}
-        openstack security group rule create --proto tcp --dst-port 80 ${SECGROUP_NAME}
-        openstack security group rule create --proto tcp --dst-port 443 ${SECGROUP_NAME}
+        os_cmd security group rule create --proto icmp ${SECGROUP_NAME}
+        os_cmd security group rule create --proto tcp --dst-port 22 ${SECGROUP_NAME}
+        os_cmd security group rule create --proto tcp --dst-port 80 ${SECGROUP_NAME}
+        os_cmd security group rule create --proto tcp --dst-port 443 ${SECGROUP_NAME}
     fi
 
-    ## create sriov port
     {% if workload_sriov | bool -%}
+    ## create sriov port
     openstack port create --vnic-type direct --network ${EXTERNAL_NET_NAME} \
         --binding-profile trusted=true ${SRIOV_PORT}
     {%- endif %}
@@ -240,14 +286,14 @@ function workload_launch {
 
     echo "Creating overcloud instance ${INSTANCE_NAME}"
     {% if workload_sriov | bool -%}
-    openstack server create  \
+    os_cmd server create  \
         --image ${IMAGE_NAME} \
         --flavor ${FLAVOR_NAME} \
         --key-name  ${KEYPAIR_NAME} \
         --port ${SRIOV_PORT} \
         ${INSTANCE_NAME}
     {% else -%}
-    openstack server create  \
+    os_cmd server create  \
         --image ${IMAGE_NAME} \
         --flavor ${FLAVOR_NAME} \
         --security-group ${SECGROUP_NAME} \
@@ -256,10 +302,9 @@ function workload_launch {
         ${INSTANCE_NAME}
     {%- endif %}
 
-    timeout_seconds=120
     elapsed_seconds=0
     while true; do
-        INSTANCE_STATUS=$(openstack server show ${INSTANCE_NAME} -f json | jq -r '.status')
+        INSTANCE_STATUS=$(os_cmd server show ${INSTANCE_NAME} -f json | jq -r '.status')
         case "${INSTANCE_STATUS}" in
             "ACTIVE")
                 echo "${INSTANCE_NAME} reached 'ACTIVE' status"
@@ -270,7 +315,7 @@ function workload_launch {
                 exit 1
         esac
         sleep 3
-        elapsed_seconds=$(expr $elapsed_seconds + 3)
+        elapsed_seconds=$((elapsed_seconds + 3))
         if [ $elapsed_seconds -ge $timeout_seconds ]; then
             echo "FAILURE: Instance failed to boot within ${elapsed_seconds} seconds"
             openstack server show ${INSTANCE_NAME} -f json 2>&1
@@ -280,55 +325,51 @@ function workload_launch {
 
     ## assign floating ip or external ip
     {% if workload_sriov | bool -%}
-    EXTERNAL_IP=$(openstack port show ${SRIOV_PORT} -f json -c fixed_ips | jq -r -c '.fixed_ips[0]["ip_address"]')
+    EXTERNAL_IP=$(os_cmd port show ${SRIOV_PORT} -f json -c fixed_ips | jq -r -c '.fixed_ips[0]["ip_address"]')
     VM_IP=${EXTERNAL_IP}
     {% else -%}
-    INSTANCE_FIP=$(openstack floating ip create ${EXTERNAL_NET_NAME} -f json | jq -r -c '.floating_ip_address' )
+    INSTANCE_FIP=$(os_cmd floating ip create ${EXTERNAL_NET_NAME} -f json | jq -r -c '.floating_ip_address' )
 
-    echo "Assign FIP[${INSTANCE_FIP}] to server ${INSTANCE_NAME}"
-    openstack server add floating ip ${INSTANCE_NAME} ${INSTANCE_FIP}
-    if [ $? -ne 0 ]; then
-        echo "Network related error detected while attaching FIP to VM. Exiting with non-zero code"
-        if [[ "${MODE}" == "sanity" ]]; then
-            sanity_teardown
-        fi
-        exit 1
+    if [ -z "${INSTANCE_FIP}" ]; then
+        echo "Cannot get a new FIP"
+        exit 66
     fi
-    VM_IP=${INSTANCE_FIP}
+    echo "Assign FIP[${INSTANCE_FIP}] to server ${INSTANCE_NAME}"
+    os_cmd server add floating ip ${INSTANCE_NAME} ${INSTANCE_FIP}
+    VM_IP="${INSTANCE_FIP}"
+
     {%- endif %}
 
     ## create and attach a volume
     ## The cinder resource must be created and available to be attach
-    CINDER_VOL_ID=$(openstack volume create --size 1 vol_${SUFFIX} -f json | jq -r .id)
-    while true; do
-        VOL_STATUS=$(openstack volume show ${CINDER_VOL_ID} -f value -c status)
-        if [[ ${VOL_STATUS} == "available" ]]; then
-            echo "The volume ${CINDER_VOL_ID} successfully created and available"
-            break
-        fi
+    CINDER_VOL_ID=$(os_cmd volume create --size 1 vol_${SUFFIX} -f json | jq -r .id)
 
-        sleep 5
-        elapsed_seconds=$(( ${elapsed_seconds} + 5 ))
+    elapsed_seconds=0
+    if [ -n "${CINDER_VOL_ID}" ]; then
+        while true; do
+            VOL_STATUS=$(os_cmd volume show ${CINDER_VOL_ID} -f value -c status)
+            if [[ ${VOL_STATUS} == "available" ]]; then
+                echo "The volume ${CINDER_VOL_ID} successfully created and available"
+                break
+            fi
 
-        if [ $elapsed_seconds -ge $timeout_seconds ]; then
-            echo "FAILURE: Failed to create the volume ${CINDER_VOL_ID}"
-            exit 1
-        fi
-    done
+            sleep 5
+            elapsed_seconds=$((elapsed_seconds + 5))
 
-    echo "Attach volume vol_${SUFFIX} to instance ${INSTANCE_NAME}"
-    openstack server add volume ${INSTANCE_NAME} ${CINDER_VOL_ID}
-
-    if [ $? -ne 0 ]; then
-        echo "Storage related error detected while attaching VOLUME to VM. Exiting with non-zero code"
-        if [[ "${MODE}" == "sanity" ]]; then
-            sanity_teardown
-        fi
-        exit 1
+            if [ $elapsed_seconds -ge $timeout_seconds ]; then
+                echo "FAILURE: Failed to create the volume ${CINDER_VOL_ID}"
+                exit 1
+            fi
+        done
+    else
+        echo "FAILURE: could not create the volume."
+        exit 65
     fi
 
+    echo "Attach volume vol_${SUFFIX} to instance ${INSTANCE_NAME}"
+    os_cmd server add volume ${INSTANCE_NAME} ${CINDER_VOL_ID}
+
     ## SSH to VM through it's floating ip or external ip
-    timeout_seconds=180
     elapsed_seconds=0
     while true; do
         # assert instance is reachable via ssh
@@ -342,12 +383,9 @@ function workload_launch {
             break
         fi
         sleep 3
-        elapsed_seconds=$(expr $elapsed_seconds + 3)
-        if [ $elapsed_seconds -ge $timeout_seconds ]; then
+        elapsed_seconds=$((elapsed_seconds + 3))
+        if [ $elapsed_seconds -ge $ssh_timeout_seconds ]; then
             echo "FAILURE: Instance failed to boot."
-            if [[ "${MODE}" == "sanity" ]]; then
-                sanity_teardown
-            fi
             exit 1
         fi
     done
@@ -373,9 +411,18 @@ if [[ "${MODE}" == "cleanup" ]]; then
 fi
 
 if [[ "${MODE}" == "sanity" ]]; then
+    trap cleanup_on_exit EXIT
     SUFFIX=$(openssl rand -hex 5)
     prepare_env
     sanity_check
     workload_launch
-    sanity_teardown
+fi
+
+if [[ "${MODE}" == "sanityfast" ]]; then
+    FAST=10
+    trap cleanup_on_exit EXIT
+    SUFFIX=$(openssl rand -hex 5)
+    prepare_env
+    sanity_check $FAST
+    workload_launch $FAST $FAST
 fi
